# Generated by Django 5.2.3 on 2025-06-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_patientreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientreport",
            name="medication",
            field=models.TextField(default="N/A"),
        ),
    ]
